### ISSUE TITLE
bug以及优化建议

### ISSUE THREAD

**Issue by seven-yu** [halo-dev/halo-theme-hux#1]
1.   CATALOG  点击无效
2.   标题都携带 #

**Comment by JobanCai** [comment]
主题很棒的，同样遇到一样的问题哦，CATALOG 点击无效，标题都携带 #

**Comment by ruibaby** [comment]
好的，非常感谢你的反馈，关于主题的问题会在halo发布1.0的时候统一解决。

**Comment by JohnNiang** [comment]
@ruibaby 这个是否已经解决了呢？

**Comment by ruibaby** [comment]
应该没有

**Comment by alexandaking** [comment]
sw.js 找不到 原作者已经更新到1.8了 建议同步更新 多谢

**Comment by ruibaby** [comment]
> sw.js 找不到 原作者已经更新到1.8了 建议同步更新 多谢

欢迎参与贡献。
