### ISSUE TITLE
评论头像不显示

### ISSUE THREAD

**Issue by wdragondragon** [halo-dev/halo-theme-hux#10]
![image](https://user-images.githubusercontent.com/47441585/61170647-dea0b280-a59e-11e9-83c4-27806ecdd8fa.png)

**Comment by sfyumi** [comment]
评论者头像这个设置你设置的是什么啊？

**Comment by wdragondragon** [comment]
问题已经解决了，是版本的问题。。

**Comment by wdragondragon** [comment]
问题已经解决了，是版本的问题。。
