### ISSUE TITLE
请问是否支持公式？

### ISSUE THREAD

**Issue by Cenbylin** [halo-dev/halo-theme-hux#16]

**Comment by sfyumi** [comment]
你说的是数学公式吗？

**Comment by Cenbylin** [comment]
> 你说的是数学公式吗？

是的，直接$$有显示问题，似乎是halo的的通病（要用```math来解决）。

想请问本主题支持直接$$包括数学公式吗

**Comment by sfyumi** [comment]
> > 你说的是数学公式吗？
> 
> 是的，直接$$有显示问题，似乎是halo的的通病（要用```math来解决）。
> 
> 想请问本主题支持直接$$包括数学公式吗

你可以在 halo 下面提 issue
