### ISSUE TITLE
所有分类的页面都无法访问

### ISSUE THREAD

**Issue by 0xTract0r** [halo-dev/halo-theme-hux#18]
如下图，所有分类都显示无法找到模板，请问是 halo 更新了1.3.x 版本的问题吗？ 
![image](https://user-images.githubusercontent.com/43313765/79426925-73d14b80-7ff6-11ea-81ae-4fa2eaed5449.png)

**Comment by ruibaby** [comment]
这主题本身就没有分类模板。

**Comment by 0xTract0r** [comment]
好吧，确实只有标签页，我再想想办法，谢谢！
